### ISSUE TITLE
missing the check for AZURE_IOT_HUB_NAME

### ISSUE THREAD

**Issue by cjdcordeiro** [SixSq/azure-iot-edge-runtime-container#2]
https://github.com/SixSq/azure-iot-edge-runtime-container/blob/9186e15200d4d8aa5b26209ef7e8941fcc3dde5e/entrypoint.sh#L44

**Comment by QuietSwami** [comment]
Fixed with the latest commit

**Comment by cjdcordeiro** [comment]
ok pls close then
